<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="10.0.2" />
    <PackageReference Include="NuGet.Packaging" Version="7.3.1" />
    <PackageReference Include="NuGet.Protocol" Version="7.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\zuroWa.Core\zuroWa.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <_ContentIncludedByDefault Remove="Views\Movie\Create.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Movie\Delete.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Movie\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Theater\Details.cshtml" />
    <_ContentIncludedByDefault Remove="Views\Theater\Index.cshtml" />
    <_ContentIncludedByDefault Remove="Areas\Identity\Pages\Account\Register.cshtml" />
  </ItemGroup>

</Project>
